/**
 * Convex auth configuration.
 *
 * Dual auth providers:
 * 1. Better Auth OIDC — production OAuth and dev BA sessions via @convex-dev/better-auth
 * 2. Custom JWT — development-only, enables JWT-based multi-persona auth
 *
 * The custom JWT provider uses a static dev keypair generated by
 * scripts/generate-dev-keys.ts. DO NOT manually edit the jwks value.
 */
import { getAuthConfigProvider } from '@convex-dev/better-auth/auth-config';

export default {
  providers: [
    getAuthConfigProvider(),
    {
      type: 'customJwt' as const,
      applicationID: 'floorplan-dev',
      issuer: 'https://floorplan-dev-auth.local',
      // AUTO-GENERATED — do not edit manually (run: npm run generate-dev-keys)
      // @generated-jwks-start
      jwks: 'data:text/plain;charset=utf-8;base64,ewogICJrZXlzIjogWwogICAgewogICAgICAia3R5IjogIlJTQSIsCiAgICAgICJuIjogInJGb0w2M3haQzlNTFBjZ21SRWhsZGFzM0JTS0NKd2pjQ29la3c1bzZBWWtoeFBGeG5lMWNaTTU5Z0FwTTBTZVFtanF1Y192c0E5UjhocHcybTB2MUxRSkJMTkJBN1pLX0FMSkhteGNWUEJ5aXF3Q3lhc1pTYWxVUXRjeTJqNHJJbDRacXNyUUUzWXdTM3JmOGNQUTVRcEgyQ2FvM3dfRHRRVWV4RHVxSEdEcThZOU4wX2J0UHRVLTVKdTBaWnZoZFpMTlNMenNWWDdsZjhyNUl5ckdHYU9kMEJVR1N1YllCQXVSeUFYUHZtTkh0elRxMDZfZkJaQnpsRDNvTG9yRmp1TVZ6VTRxZWNQTEJYckJ3ZTVtdDg2cWRpbjllZlM4eGg1dFJrS1FtWXdXeWFHeWhEbW1PX2NjWWF5M1hNaVRCRC15WmJxYVY2Ul8xWl8yZDQ3dEpQUSIsCiAgICAgICJlIjogIkFRQUIiLAogICAgICAidXNlIjogInNpZyIsCiAgICAgICJraWQiOiAiZmxvb3JwbGFuLWRldi1rZXkiLAogICAgICAiYWxnIjogIlJTMjU2IgogICAgfQogIF0KfQ==',
      // @generated-jwks-end
      algorithm: 'RS256' as const,
    },
  ],
};
