/**
 * Convex auth configuration.
 *
 * Dual auth providers:
 * 1. Better Auth OIDC — production OAuth and dev BA sessions via @convex-dev/better-auth
 * 2. Custom JWT — development-only, enables JWT-based multi-persona auth
 *
 * The custom JWT provider uses a static dev keypair generated by
 * scripts/generate-dev-keys.ts. DO NOT manually edit the jwks value.
 */
import { getAuthConfigProvider } from '@convex-dev/better-auth/auth-config';

export default {
  providers: [
    getAuthConfigProvider(),
    {
      type: 'customJwt' as const,
      applicationID: 'floorplan-dev',
      issuer: 'https://floorplan-dev-auth.local',
      // AUTO-GENERATED — do not edit manually (run: npm run generate-dev-keys)
      // @generated-jwks-start
      jwks: 'data:text/plain;charset=utf-8;base64,ewogICJrZXlzIjogWwogICAgewogICAgICAia3R5IjogIlJTQSIsCiAgICAgICJuIjogInNjYUt5UFFUSThXYkdZUVFYVkZoNjMtOU9LWGNVaGxYZ21OaWJFSnNSbU90NjFTSDV0ckgwSXlhZUxfNXpEOFJ6amx2cWsteTU4d2NFRTMtTUhrSDJXZWtYYi16ZGVwU2p4ZW9DZnhhUk5pNG0xTUt1QzVNcVFHLVhIWERsR0Z3aWx4TmV4NC1hQWM5OEw2MDdIZXZGcnQ5bWNuaDdHY3NEeTRWRlh4RF9uZWNuNGVCMmtGanUzX1p2Qy1UQm5ETXprcmVIYXdnRTNZXzBJV0ZQTUdKQW1Cdl9PdW80Z0lrNmx3YXZQcFFWR0lGSG9YV3hOSkJ0VlNnbVljWUphUFpDZnk5NWY1NlJvMGFRdzQ1ZUxKM3FkZGFPaTh6RXhkcURrNXkwNG5tQnpRdVAxMUM4MWE0c0JFTzZUR2dXa0RPTzVTa0puVFZNVlc2ckVjbHVLeFQ0dyIsCiAgICAgICJlIjogIkFRQUIiLAogICAgICAidXNlIjogInNpZyIsCiAgICAgICJraWQiOiAiZmxvb3JwbGFuLWRldi1rZXkiLAogICAgICAiYWxnIjogIlJTMjU2IgogICAgfQogIF0KfQ==',
      // @generated-jwks-end
      algorithm: 'RS256' as const,
    },
  ],
};
