/**
 * Convex auth configuration.
 *
 * Dual auth providers:
 * 1. Better Auth OIDC — production OAuth and dev BA sessions via @convex-dev/better-auth
 * 2. Custom JWT — development-only, enables JWT-based multi-persona auth
 *
 * The custom JWT provider uses a static dev keypair generated by
 * scripts/generate-dev-keys.ts. DO NOT manually edit the jwks value.
 */
import { getAuthConfigProvider } from '@convex-dev/better-auth/auth-config';

export default {
  providers: [
    getAuthConfigProvider(),
    {
      type: 'customJwt' as const,
      applicationID: 'floorplan-dev',
      issuer: 'https://floorplan-dev-auth.local',
      // AUTO-GENERATED — do not edit manually (run: npm run generate-dev-keys)
      // @generated-jwks-start
      jwks: 'data:text/plain;charset=utf-8;base64,ewogICJrZXlzIjogWwogICAgewogICAgICAia3R5IjogIlJTQSIsCiAgICAgICJuIjogIjRzUTRHRDR0X09aTU5QYk04UUUxQnM5aWxkR0ZWRTZ2ZWFsdmg1RlRHamkwblE5b3RIeE9CR0NJWm1QWWUyYTV5am9RRVJMVkFudmRibVRPWFBDb2xVekVoajhvc3NCcm02eUlpV3hFWE1jZWpBa2s1bmlEUXhoVGVvUXA0eWYyc1hzNVp2RERTeldWM1pZeXUyWldmM2JieGN1Q3pwX1luOVFpVFRvS0d6dTdDX0wzMHhEaGxBZGRUU1pLMFBQYlpuQ3k5d1JrSzJkYWRnWGUyZ0lVQWJ1bXFjQ01tY1oxX1ZjaFM2Nkk1WnFqWDdiRk9ZTnhlMzVrQkthcTNmZWd2b3pzUUVqWHExM2tGeU52OFctVWZRR19wUmx6S3ktWm1oSGdRVVZzdW1wQ3o5eXVRR3AyZng0LTBkOF9XenZUTUNjTjFROWV5bUc3RklqNnBrWFh6USIsCiAgICAgICJlIjogIkFRQUIiLAogICAgICAidXNlIjogInNpZyIsCiAgICAgICJraWQiOiAiZmxvb3JwbGFuLWRldi1rZXkiLAogICAgICAiYWxnIjogIlJTMjU2IgogICAgfQogIF0KfQ==',
      // @generated-jwks-end
      algorithm: 'RS256' as const,
    },
  ],
};
