#!/usr/bin/env node
/**
 * generate_variations.mjs — emit 2-3 alternative layouts from one brief.
 *
 * Runs the same brief through multiple packing strategies (linear,
 * L-shape, central-corridor, rows) and returns their DSLs side-by-side.
 * Useful for offering design alternatives before committing to one.
 *
 * Usage:
 *   node generate_variations.mjs --brief brief.json
 *     [--strategies linear,l-shape,central-corridor,rows]
 *     [--out-dir variations/]
 *     [--name-pattern "v{n}"]   # default: variation-{strategy}
 *                                # placeholders: {n} = 1-indexed counter,
 *                                # {strategy} = strategy slug.
 *     [--render]                 # also produce <name>.png for each variation
 *     [--allow-low-confidence]
 *
 * Default strategies: linear, l-shape, central-corridor.
 *
 * Output `data` shape:
 *   {
 *     variations: [
 *       {
 *         strategy: "linear",
 *         label: "Linear (single wide row)",
 *         dsl: "...",
 *         path: "/out/variation-linear.floorplan" | null,
 *         summary: { roomCount, totalArea, unit, areaUnit, bbox: { w, h } }
 *       },
 *       ...
 *     ]
 *   }
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { parseArgs, emitOk, emitValidationError, run } from './_lib.mjs';
import {
  checkConfidence,
  renderDsl,
  selectAnchor,
  STRATEGIES,
} from './_layout_lib.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

const DEFAULT_STRATEGIES = ['linear', 'l-shape', 'central-corridor'];

function boundingBox(placements) {
  if (placements.length === 0) return { w: 0, h: 0 };
  let maxX = 0;
  let maxY = 0;
  for (const p of placements) {
    if (!p.pos) continue;
    const right = p.pos.x + p.size.width;
    const bottom = p.pos.y + p.size.height;
    if (right > maxX) maxX = right;
    if (bottom > maxY) maxY = bottom;
  }
  return { w: maxX, h: maxY };
}

function expandName(pattern, { n, strategy }) {
  return pattern.replace(/\{n\}/g, String(n)).replace(/\{strategy\}/g, strategy);
}

run(async () => {
  const args = parseArgs();
  const allowLow = args['allow-low-confidence'] === true;
  const outDir = args['out-dir'] ? resolve(args['out-dir']) : null;
  const namePattern = args['name-pattern'] ?? 'variation-{strategy}';
  const shouldRender = args.render === true;

  const strategies = args.strategies
    ? String(args.strategies).split(',').map((s) => s.trim())
    : DEFAULT_STRATEGIES;

  const unknown = strategies.filter((s) => !STRATEGIES[s]);
  if (unknown.length > 0) {
    emitValidationError([
      {
        message: `Unknown strategy(ies): ${unknown.join(', ')}. Known: ${Object.keys(STRATEGIES).join(', ')}`,
      },
    ]);
  }

  if (!args.brief) emitValidationError([{ message: 'Missing --brief <brief.json>' }]);

  let brief;
  try {
    brief = JSON.parse(readFileSync(args.brief, 'utf-8'));
  } catch (err) {
    emitValidationError([{ message: `Could not read --brief: ${err.message}` }]);
  }

  if (!Array.isArray(brief.rooms) || brief.rooms.length === 0) {
    emitValidationError([{ message: "Brief must include a non-empty 'rooms' array." }]);
  }

  const seen = new Set();
  for (const r of brief.rooms) {
    if (seen.has(r.name)) emitValidationError([{ message: `Duplicate room name: ${r.name}` }]);
    seen.add(r.name);
  }

  const confFindings = checkConfidence(brief, allowLow);
  if (confFindings.length > 0) emitValidationError(confFindings, null, []);

  if (outDir) mkdirSync(outDir, { recursive: true });

  const rooms = selectAnchor(brief.rooms);

  const variations = [];
  let n = 0;
  for (const stratName of strategies) {
    n += 1;
    const { packer, label } = STRATEGIES[stratName];
    const placements = packer([...rooms]);
    const dsl = renderDsl(brief, placements, [
      `Generated by generate_variations.mjs (${label}).`,
      `Alternative: ${stratName}. Rerun validate.mjs + design_critic.mjs.`,
    ]);

    const bbox = boundingBox(placements);
    let path = null;
    let pngPath = null;
    if (outDir) {
      const baseName = expandName(namePattern, { n, strategy: stratName });
      path = join(outDir, `${baseName}.floorplan`);
      writeFileSync(path, dsl);
      if (shouldRender) {
        pngPath = join(outDir, `${baseName}.png`);
        try {
          execFileSync('node', [
            join(SCRIPT_DIR, 'render.mjs'),
            path,
            '--out', pngPath,
          ], { stdio: 'pipe' });
        } catch (err) {
          // Surface render failure via the variation entry; do not abort the
          // rest of the variations.
          pngPath = { error: String(err.message ?? err).slice(0, 500) };
        }
      }
    }

    variations.push({
      strategy: stratName,
      label,
      dsl,
      path,
      pngPath,
      summary: {
        strategy: stratName,
        roomCount: placements.length,
        totalArea: placements.reduce((s, p) => s + p.size.width * p.size.height, 0),
        bbox,
        unit: brief.unit ?? 'ft',
        areaUnit: brief.areaUnit ?? 'sqft',
      },
    });
  }

  emitOk({ variations });
});
