#!/usr/bin/env node
/**
 * program_to_skeleton.mjs — turn a program brief into a starter .floorplan.
 *
 * The brief format is documented in program_brief.schema.json. Two shapes
 * are supported:
 *   - minimal:  { rooms: [{ name, kind }, ...] }
 *   - rich:     includes sizes, positions, wall types, connections, etc.
 *
 * Usage:
 *   node program_to_skeleton.mjs --brief brief.json --out plan.floorplan
 *   node program_to_skeleton.mjs --brief brief.json                  # envelope only
 *   node program_to_skeleton.mjs --brief brief.json --allow-low-confidence
 *   node program_to_skeleton.mjs --brief brief.json --row-width 34   # packing width
 *   node program_to_skeleton.mjs --brief brief.json --floors 2       # multi-floor:
 *                                                                    # public on
 *                                                                    # ground, private
 *                                                                    # upstairs, with
 *                                                                    # an auto-stacked
 *                                                                    # stair core +
 *                                                                    # vertical links.
 *
 * Uses the "rows" strategy (left-to-right, wraps at row-width). Call
 * generate_variations.mjs for linear / L-shape / central-corridor
 * alternatives.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { parseArgs, emitOk, emitValidationError, run } from './_lib.mjs';
import {
  checkConfidence,
  packRowWise,
  partitionRoomsByFloor,
  renderDsl,
  renderMultiFloorDsl,
  selectAnchor,
} from './_layout_lib.mjs';

run(async () => {
  const args = parseArgs();
  const allowLow = args['allow-low-confidence'] === true;
  const rowWidth = args['row-width'] ? Number(args['row-width']) : 34;
  const floorsRequested = args.floors !== undefined ? Number(args.floors) : null;

  if (!args.brief) emitValidationError([{ message: 'Missing --brief <brief.json>' }]);

  let brief;
  try {
    brief = JSON.parse(readFileSync(args.brief, 'utf-8'));
  } catch (err) {
    emitValidationError([{ message: `Could not read --brief: ${err.message}` }]);
  }

  if (!Array.isArray(brief.rooms) || brief.rooms.length === 0) {
    emitValidationError([{ message: "Brief must include a non-empty 'rooms' array." }]);
  }

  const seen = new Set();
  for (const r of brief.rooms) {
    if (seen.has(r.name)) emitValidationError([{ message: `Duplicate room name: ${r.name}` }]);
    seen.add(r.name);
  }

  const confFindings = checkConfidence(brief, allowLow);
  if (confFindings.length > 0) emitValidationError(confFindings, null, []);

  const declaredFloorCount = Array.isArray(brief.floors) ? brief.floors.length : 0;
  const floorCount = Number.isFinite(floorsRequested) && floorsRequested > 0
    ? floorsRequested
    : Math.max(1, declaredFloorCount);

  if (floorCount === 1) {
    const rooms = selectAnchor(brief.rooms);
    const placements = packRowWise(rooms, { rowWidth });
    const dsl = renderDsl(brief, placements, [
      'Generated by program_to_skeleton.mjs (rows strategy).',
      'Edit with modify.mjs or by hand; rerun validate.mjs + design_critic.mjs.',
    ]);
    const summary = {
      strategy: 'rows',
      floors: 1,
      anchor: rooms[0]?.name ?? null,
      floor: brief.floors?.[0]?.id ?? 'GroundFloor',
      roomCount: rooms.length,
      totalArea: placements.reduce((s, p) => s + p.size.width * p.size.height, 0),
      unit: brief.unit ?? 'ft',
      areaUnit: brief.areaUnit ?? 'sqft',
    };
    if (args.out) {
      const outPath = resolve(args.out);
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, dsl);
      emitOk({ dsl, path: outPath, summary });
    } else {
      emitOk({ dsl, summary });
    }
    return;
  }

  const { byFloor, floors } = partitionRoomsByFloor(brief, { floors: floorCount });

  // Stair core: pinned at (0, 0) on every floor so it stacks identically
  // and shares walls with whichever room ends up at x=stairWidth. Each
  // floor gets a unique room name (validator scopes connections globally
  // by name, so identical names would alias door positions across floors).
  //
  // The room's *length* (Y dim) is derived from the rise of the floor
  // below + the standard step counts + landings, matching the
  // stair_through_walls / stair_landing_clearance critic rules. With a
  // 10 ft floor at 7"/11" (residential), 18 steps × 11" = 16.5 ft of run
  // plus 2 × 3 ft landings = 22.5 ft (rounded up to 23). Override
  // `--stair-code commercial` (or `ada`) to use 4 ft landings.
  const stairCodeArg = (args['stair-code'] ?? 'residential').toLowerCase();
  const stairCode = ['residential', 'commercial', 'ada'].includes(stairCodeArg)
    ? stairCodeArg
    : 'residential';
  const riserFt = stairCode === 'residential' ? 7 / 12 : 7 / 12;
  const treadFt = stairCode === 'residential' ? 11 / 12 : 11 / 12;
  const landingFt = stairCode === 'residential' ? 3 : 4;
  const stairWidth = 6;
  const stairElementWidth = 4;
  const groundHeight = floors[0]?.height ?? 10;
  const stepCount = Math.max(1, Math.ceil(groundHeight / riserFt));
  const runLength = stepCount * treadFt;
  const stairCoreLength = Math.ceil(runLength + 2 * landingFt);
  const stairY = landingFt; // bottom landing lives at y in [0, landingFt]
  const roomNamesByFloor = new Map(
    floors.map((f) => [f.id, `${f.id}StairCore`]),
  );
  const stairCore = {
    roomName: 'StairCore',
    roomNamesByFloor,
    stairName: 'MainStair',
    x: 0,
    y: 0,
    width: stairWidth,
    height: stairCoreLength,
    stairX: 1,
    stairY,
    stairWidth: stairElementWidth,
    stairCode,
    stepCount,
    runLength,
    landing: landingFt,
  };

  // Pack each floor with an x-offset of stairWidth so the stair core slots
  // in at the left edge without overlapping any room.
  const floorPlacements = new Map();
  for (const floor of floors) {
    const floorRooms = selectAnchor(byFloor.get(floor.id) ?? []);
    const packed = packRowWise(floorRooms, { rowWidth });
    for (const p of packed) {
      if (p.pos) p.pos = { x: p.pos.x + stairWidth, y: p.pos.y };
    }
    floorPlacements.set(floor.id, packed);
  }

  // Straight stairs need egress connections at *both* landing strips on
  // every floor that boards or arrives via the stair (see the
  // stair_landing_egress critic rule). The renderer hard-codes
  // `shape straight toward top`, which means the boarding (bottom-step)
  // landing sits at large Y and the arrival (top-step) landing at small Y
  // (within the StairCore room's local coords).
  //
  // To make both landing connections fit on the same anchor wall, we
  // stretch each non-terminus floor's anchor (first row, first room) so
  // it spans the full StairCore height. The anchor is intentionally
  // oversized; users are expected to refine the layout via modify.mjs or
  // by hand once the brief is fleshed out.
  for (let i = 0; i < floors.length; i++) {
    const isTerminus = i === floors.length - 1;
    if (isTerminus) continue;
    const placements = floorPlacements.get(floors[i].id) ?? [];
    if (placements.length === 0) continue;
    const anchor = placements[0];
    if (
      anchor?.pos &&
      anchor?.size &&
      anchor.pos.y === 0 &&
      anchor.size.height < stairCore.height
    ) {
      anchor.size = { ...anchor.size, height: stairCore.height };
    }
  }

  // Connector type used for the stair-core ↔ anchor connections. The
  // brief defaults to residential, which gets `opening` so the landings
  // stay walk-throughs (avoids the dead-end + double-door problem the
  // stair_landing_egress rule guards against). Commercial / ADA cores
  // need a rated door instead.
  const connectorType = stairCode === 'residential' ? 'opening' : 'door';

  // Place auto-connections on the stair core's right wall at the
  // *boarding* (bottom-step) and *arrival* (top-step) landing strips.
  // For `shape straight toward top` the stair tread occupies
  // y=[stairY, stairY + runLength]; the strips bracket that range with
  // depth = landingFt:
  //   - arrival (top-step) strip = [stairY − landing, stairY] → centre at
  //     stairY − landing/2
  //   - boarding (bottom-step) strip = [stairY + runLength,
  //     stairY + runLength + landing] → centre at
  //     stairY + runLength + landing/2
  //
  // The DSL specifies `at <pos>%` as a fraction of the *overlap* between
  // the two facing walls (see geometry-utils#calculatePositionOnWallOverlap),
  // not as a fraction of the stair-core's full wall. So when we connect
  // StairCore.right (y=[0, 23]) to a 6 ft Foyer at y=[0, 6], the arrival
  // target y=1.5 becomes 25% of the [0, 6] overlap. With a 23 ft anchor
  // the same target becomes ≈ 6.5%; the boarding target y=21 becomes
  // ≈ 91.3%.
  const doorWidth = 3; // CONFIG_DEFAULTS.doorWidth in ft
  const targetArrivalY = stairCore.y + stairY - landingFt / 2;
  const targetBoardingY = stairCore.y + stairY + runLength + landingFt / 2;
  const arrivalStripRange = [targetArrivalY - landingFt / 2, targetArrivalY + landingFt / 2];
  const boardingStripRange = [targetBoardingY - landingFt / 2, targetBoardingY + landingFt / 2];

  /**
   * Compute the `at <pos>%` value to land an opening at `targetY` on the
   * shared overlap of stair-core.right and otherRoom.left, ensuring the
   * full door width stays inside `stripRange`. Returns null if the
   * overlap or strip can't host the door.
   */
  function computeStairCoreDoorPctAt(otherPlacement, targetY, stripRange) {
    if (!otherPlacement?.pos || !otherPlacement?.size) return null;
    const otherY1 = otherPlacement.pos.y;
    const otherY2 = otherY1 + otherPlacement.size.height;
    const stairY1 = stairCore.y;
    const stairY2 = stairCore.y + stairCore.height;
    const overlapStart = Math.max(stairY1, otherY1);
    const overlapEnd = Math.min(stairY2, otherY2);
    const overlapLen = overlapEnd - overlapStart;
    if (overlapLen < doorWidth) return null;
    // The door (width = doorWidth) must sit fully inside both the wall
    // overlap *and* the landing strip, otherwise the critic will reject
    // it as not serving the strip.
    const minCenter = Math.max(overlapStart, stripRange[0]) + doorWidth / 2;
    const maxCenter = Math.min(overlapEnd, stripRange[1]) - doorWidth / 2;
    if (maxCenter < minCenter - 0.001) return null;
    const clamped = Math.min(maxCenter, Math.max(minCenter, targetY));
    const pct = ((clamped - overlapStart) / overlapLen) * 100;
    return Number(Math.max(0, Math.min(100, pct)).toFixed(2));
  }

  const connectionsByFloor = new Map(floors.map((f) => [f.id, []]));
  for (let i = 0; i < floors.length; i++) {
    const floor = floors[i];
    const isOrigin = i === 0;
    const isTerminus = i === floors.length - 1;
    const placements = floorPlacements.get(floor.id) ?? [];
    if (placements.length === 0) continue;
    const anchorPlacement = placements[0];
    const anchorRoom = anchorPlacement.room;
    const coreName = roomNamesByFloor.get(floor.id);
    const buf = connectionsByFloor.get(floor.id);

    if (isOrigin) {
      buf.push(`  connect ${anchorRoom.name}.top to outside door at 50%`);
    }

    // Arrival landing (small Y for `toward top`) — needed on every floor
    // that something climbs up to. That excludes the origin floor.
    if (!isOrigin) {
      const arrivePct = computeStairCoreDoorPctAt(
        anchorPlacement,
        targetArrivalY,
        arrivalStripRange,
      );
      if (arrivePct !== null) {
        buf.push(
          `  connect ${coreName}.right to ${anchorRoom.name}.left ${connectorType} at ${arrivePct}%`,
        );
      }
    }

    // Boarding landing (large Y for `toward top`) — needed on every floor
    // that boards an upward stair. That excludes the terminus floor.
    if (!isTerminus) {
      const boardPct = computeStairCoreDoorPctAt(
        anchorPlacement,
        targetBoardingY,
        boardingStripRange,
      );
      if (boardPct !== null) {
        buf.push(
          `  connect ${coreName}.right to ${anchorRoom.name}.left ${connectorType} at ${boardPct}%`,
        );
      }
    }
  }

  const dsl = renderMultiFloorDsl({
    brief,
    floors,
    floorPlacements,
    stairCore,
    connectionsByFloor,
    headerLines: [
      `Generated by program_to_skeleton.mjs (rows strategy, ${floors.length} floors).`,
      'Stair core auto-stacked at consistent (x, y) on every floor.',
      'Edit with modify.mjs or by hand; rerun validate.mjs + design_critic.mjs.',
    ],
  });

  const summary = {
    strategy: 'rows',
    floors: floors.length,
    floorIds: floors.map((f) => f.id),
    stairCore: {
      name: stairCore.stairName,
      x: stairCore.x,
      y: stairCore.y,
      width: stairCore.width,
      height: stairCore.height,
      stepCount: stairCore.stepCount,
      runLength: Number(stairCore.runLength.toFixed(2)),
      landing: stairCore.landing,
      stairCode: stairCore.stairCode,
      connectorType,
    },
    roomCount: brief.rooms.length,
    totalArea: [...floorPlacements.values()]
      .flat()
      .reduce((s, p) => s + p.size.width * p.size.height, 0),
    unit: brief.unit ?? 'ft',
    areaUnit: brief.areaUnit ?? 'sqft',
  };

  if (args.out) {
    const outPath = resolve(args.out);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, dsl);
    emitOk({ dsl, path: outPath, summary });
  } else {
    emitOk({ dsl, summary });
  }
});
